#!/bin/sh

# Copyright 2025 IBM Corporation and others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

# Pre-commit hook to check copyright messages
# This hook runs the check-copyright.sh script against the staged changes
# Get the root directory of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)
COPYRIGHT_SCRIPT="$ROOT_DIR/scripts/check-copyright2.sh"

# # Check if the copyright script exists
# if [ ! -f "$COPYRIGHT_SCRIPT" ]; then
#     echo "Error: Copyright check script not found at $COPYRIGHT_SCRIPT"
#     exit 1
# fi

# Run the copyright check against the staged changes.
# If this fails, the hook will fail and stop the commit.
$COPYRIGHT_SCRIPT --staged
