/*
 * Copyright 2026 IBM Corporation and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an \"AS IS\" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

dependencies {
  // provided 'org.osgi:org.osgi.core:5.0.0'
  implementation 'org.apache.bcel:bcel:6.6.0'
  implementation project(":yoko-osgi")
  implementation files(project(":yoko-osgi").sourceSets.main.output)
  implementation project(":yoko-util")
  implementation files(project(":yoko-util").sourceSets.main.output)
  implementation project(":yoko-spec-corba")
  implementation files(project(":yoko-spec-corba").sourceSets.main.output)
  implementation project(":yoko-rmi-spec")
  implementation files(project(":yoko-rmi-spec").sourceSets.main.output)
  compileOnly project(":jdk-supplement")
}

jar {
  exclude '**/*.class'
}

javadoc {
  // Exclude SunMiscFilterAdapter which uses sun.misc.ObjectInputFilter (Java 8 only)
  // This class is not available in Java 9+ where java.io.ObjectInputFilter is used instead
  exclude '**/SunMiscFilterAdapter.java'
}
